ZAPPA_FILE_NAME = 'zappa_settings.json'
FLASK_FILE = 'flask_api.py'
THAMPI_APP_FILE = 'thampi-app.py'
THAMPI_APP = 'thampi-app.app'
PROJECT_NAME = 'project_name'
REGION = 'aws_region'
THAMPI = 'thampi'
MODEL_FILE = 'model.pkl'

PROPERTIES_FILE = THAMPI + '.json'
ZAPPA_BUCKET = 's3_bucket'